name: demo

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This should be inside the job definition

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: my-artifact  # Name of the artifact
          path: build/       # Path to the files or directory to upload
          if-no-files-found: warn  # Optional: warn, error, or ignore

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store credentials securely
          pathtoad: ${{ secrets.NAME }}
  sekhar:
     runs-on: ubuntu-latest
     steps:
       - name: frmo
         run: echo "This is sekher"
       - name: demo
         run: touch one.txt
         
     
